version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    post_install:
      - jupyter-book build notebooks

python:
  install:
    - requirements: notebooks/requirements.txt
    - path: .

formats: []
